### ISSUE TITLE
withRouter syntax help

### ISSUE THREAD

**Issue by tbrannam** [elsassph/haxe-react-router#2]
I'm looking to extended some additional Router externs to it's appropriate equivalent in Haxe.

Currently I'm working through some React Tutorials with an auth-flow.
(https://github.com/ReactTraining/react-router/blob/v3/examples/auth-flow/app.js), I am trying to figure out how to express the `Login` class in terms of Haxe and and usage that would still satisfy 

`<Route path="login" getComponent=${RouteBundle.load(R.withRouter(LoginView))} />`

```
@:jsRequire('react-router', 'withRouter')
extern class R {
        static function withRouter<T>(wrappedComponent:T): T;
}
```

**Comment by elsassph** [comment]
You must apply `withRouter` HOC after the class is loaded.

To keep using `RouteBundle.load` you can wrap the `LoginView`:
```
<Route path="login" getComponent=${RouteBundle.load(LoginContainer)} />

class LoginContainer extends ReactComponent {
    static var LoginViewWithRouter = R.withRouter(LoginView);
    override function render() {
        return jsx('<LoginViewWithRouter {...props} />
    }
}
```
Otherwise you have to use `Bundle.load` promise and follow the `getComponent` API so you can call `R.withRouter` when the class is loaded. Note that you want to avoid calling the HOC on each render.

**Comment by tbrannam** [comment]
Excellent!  worked after I adjusted my extern definition.   Need to read more on HOC, thanks for the help.

```
@:jsRequire('react-router')
extern class R {
        static function withRouter<T>(wrappedComponent:T): T;
}
```
